CC := /home/ssingh/prefix/bin/clang
CFLAGS := -O2 -pthread -D_XOPEN_SOURCE=500 -D_POSIX_C_SOURCE=200112 -std=c11 -g -fno-strict-aliasing -mllvm -x86-smda -mllvm -max-smda-nodes=10000000 -mllvm -careful -I/home/ssingh/Splash-3/hooks/src/include 
LDFLAGS := -lm -static

# BASEDIR needs to be set to the same directory as this Makefile
# BASEDIR := $(HOME)/Splash-3/codes
BASEDIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
MACROS := $(BASEDIR)/pthread_macros/pthread.m4.stougie
M4 := m4 -Ulen -Uindex

ifndef BASEDIR
$(error Please define the BASEDIR variable)
endif

x = *

$(TARGET): $(OBJS) $(EXTRADEPS)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJS) $(LDFLAGS)

clean:
	rm -rf *.c *.h *.o $(TARGET)

%.h: %.h.in
	$(M4) $(MACROS) $< > $@

%.c: %.c.in
	$(M4) $(MACROS) $< > $@

%.o: %.c $(EXTRADEPS)
	$(CC) -c $(CFLAGS) $<
